development:
  adapter: postgresql
  encoding: utf8
  database: Belvedere
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: Belvedere_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432